import 'package:flutter/material.dart';
//COLOR
const cTransparent = Colors.transparent;
const btnBlue = Color(0xFF4625C3);
const lightGrey = Color(0x2D3C3C43);
const white = Color(0xFFFAFAFA);
const textWhite = Color(0xFFF8F8F8);
const black = Colors.black;
const darkWhite = Color(0xFFF3F3F3);
const purple = Color(0xFFBB8AFF);
const darkPurple = Color(0xFF9A63FF);
const lightblue = Color(0xFF69CDDA);
const darkBlue = Color(0xFF635AFF);
const red = Colors.red;
const orange = Colors.orange;
const diaperColor = Color(0xFFC2C2C2);
const grey = Colors.grey;

//TEXT
const mTitle = "Baby Tracker";
const btnNext = "Next";
const btnStart = "Start";
const getPremium = 'Get Premium';
const inappText1 = 'Share the care';
const inappText2 = 'All-in-one baby tracker';
const inappText3 = 'Watch your babys growth';
const camera = "Camera";
const gallery = "Gallery";
const continueButton = "Continue";
const babyFullName = 'Baby Full Name';
const birthDate = 'Birth Date';
const timeOfBirth = 'Time of Birth';
const dueDate = 'Due Date';
const editProfile = 'Edit Profile';
const feeding = 'Feeding';
const diaper = 'Diaper Change';
const sleep = 'Sleep';
const ok = "OK";
const cancel = "cancel";
const poppins = 'Poppins';
const delete = "Delete";
const onboardingTitle1 = "Track Your Baby's\nActivities with Ease";
const onboardingSubTitle1 =
    "Get started with tracking your baby's\nfeedings, diaper changes, sleep patterns,\nand more...";
const onboardingTitle2 = 'Learn About Your\nBaby';
const onboardingSubTitle2 =
    "Customize your baby's profile, set\nreminders for important activities, and\nview detailed reports on your baby's rogress ";
const onboardingTitle3 = 'Stay Connected \nwith Caregivers';
const onboardingSubTiitle3 =
    "Share access to your baby's tracker with\nfamily members, babysitters, or healthcare\nproviders ";
const snackbarMassageInaap = "Please choose the appropriate Premium package!";
const errorContent = "Please make sure you fill out all fields completely";
const errorTitle = "Missing or incorrect entry!";
const settings = "Settings";
const rateUs = "Rate Us";
const termsOfUse = "Terms of Use";
const privacyPolicy = "Privacy Policy";
const contactUs = "Contact Us";
const restorePurchase = "Restore Purchase";
const time = "Time";
const amount = "Amount(ml)";
const note = "Note";
const save = "Save";
const diaperChange = "Diaper Change";
const fellSleep = "Fell Sleep";
const diaperStatus = 'Diaper Status';
const wakeApp = "Wake Up";
const calender = "Calendar";
const all = "All";
const diaperIsempty = "There is no content available at the moment.";
const feedingNote = "Feeding Note";
const diaperNote = "Diaper Note";
const sleepNote = "Sleep Note";
const notee = " Note";
const snackBarText = "Choose a premium plan to view the opportunities.";
const weekly = "Weekly";
const weekly$ = "\$12";
const monthly = "Monthly";
const monthly$ = "\$25";
const annual = "Annual";
const annual$ = "\$150";
const premiumTextMessage =
    "Premium support for your baby's development, every step of the way.";

//IMAGE
const onboardingImg1 = "assets/images/onbording1.png";
const onboardingImg2 = "assets/images/onbording2.png";
const onboardingImg3 = "assets/images/onbording3.png";
const inappImgExit = "assets/images/inapp3.png";
const inappImageBaby = "assets/icons/appicon.png";
const inappImageDot = "assets/images/inapp2.png";
const settingsImg1 = "assets/images/stng0.png";
const settingsImg2 = "assets/images/stng1.png";
const settingsImg3 = "assets/images/stng2.png";
const settingsImg4 = "assets/images/stng3.png";
const settingsImg5 = "assets/images/stng4.png";
const settingsImg6 = "assets/images/stng5.png";
const feedingIcon = "assets/images/feedinggg.png";
const diaperIcon = "assets/images/diaperrr.png";
const sleepIcon = "assets/images/sleeppp.png";
const calenderImg = "assets/icons/file.png";
const settngImg = "assets/icons/stng.png";
